version: "3"

services:
  n8n:
    image: n8nio/n8n
    restart: always
    ports:
      - "5678:5678"
    environment:
      - GENERIC_TIMEZONE=America/Caracas
      - N8N_LISTEN_ADDRESS=0.0.0.0
      - N8N_HOST=n8n-on-render.onrender.com   # Reemplazá con el subdominio que te da Render
      - WEBHOOK_URL=https://n8n-on-render.onrender.com # Igual que arriba pero con https
      - N8N_SKIP_WEBHOOK_DEREGISTRATION_SHUTDOWN=true
      - N8N_SECURE_COOKIE=false
    volumes:
      - n8n_data:/home/node/.n8n

volumes:
  n8n_data:
