version: '3.8'

services:
  n8n:
    image: n8nio/n8n
    restart: always
    ports:
      - "5678:5678"
    environment:
      - GENERIC_TIMEZONE=America/Caracas
      - N8N_LISTEN_ADDRESS=0.0.0.0
      - N8N_HOST=noted-one-lab.ngrok-free.app
      - WEBHOOK_URL=https://noted-one-lab.ngrok-free.app
      - N8N_SKIP_WEBHOOK_DEREGISTRATION_SHUTDOWN=true
      - N8N_SECURE_COOKIE=false
    volumes:
      - n8n_data:/home/node/.n8n

volumes:
  n8n_data:
